--<DS_SCRIPT>
-- DESCRIÇÃO..: Criar flag 'SN_INCREMENTA' para sinalizar se as vias das carteiras de um lote deverá ser incrementadas.
-- RESPONSAVEL: Elias Santana
-- DATA.......: 05/10/2020
-- APLICAÇÃO..: MVS
--</DS_SCRIPT>
--<USUARIO=DBAPS>
/
ALTER TABLE DBAPS.LOTE_CARTEIRA ADD (SN_INCREMENTA VARCHAR2(1) DEFAULT 'S' NOT NULL)
/
ALTER TABLE DBAPS.LOTE_CARTEIRA
    ADD CONSTRAINT cnt_sn_incre_ck CHECK (
      SN_INCREMENTA IN ('S','N')
    )
/
COMMENT ON COLUMN DBAPS.LOTE_CARTEIRA.SN_INCREMENTA IS 'FLAG PARA INDICAR SE AS VIAS DEVERÃO SER INCREMENTADAS'
/

