--<DS_SCRIPT>
-- DESCRIÇÃO..: Adiciona os grupos e itens de glosa conforme tabela 38 padrão tiss 07/2021
-- RESPONSAVEL: Elias Santana
-- DATA.......: 06/11/2021 19:08
-- APLICAÇÃO..: MVSAUDE   CIMP-27723
--</DS_SCRIPT>
--<USUARIO=DBAPS>
DECLARE
      --Retorna os Grupos com a descrição incorreta
      CURSOR cGruposGlosa  IS
      SELECT cd_grupo_motivo_glosa,
         ds_grupo_motivo_glosa,
         DS_GRUPO FROM (
          SELECT cd_grupo_motivo_glosa,
                ds_grupo_motivo_glosa,
                CASE cd_grupo_motivo_glosa
                  when  1 then 'ELEGIBILIDADE'
                  when  2 then 'PROTOCOLO'
                  when  3 then 'PRESTADOR'
                  when  4 then 'GUIA'
                  when  5 then 'AUTORIZAÇÃO / SOLICITAÇÃO'
                  when  6 then 'DIAGNÓSTICO'
                  when  7 then 'ATENDIMENTO'
                  when  8 then 'REGRA DE VALORIZAÇÃO'
                  when  9 then 'PROCEDIMENTO'
                  when 10 then 'DIÁRIA'
                  when 11 then 'MATERIAL'
                  when 12 then 'MEDICAMENTO'
                  when 13 then 'OPM'
                  when 14 then 'GASES MEDICINAIS'
                  when 15 then 'TAXAS E ALUGUÉIS'
                  when 16 then 'PROCEDIMENTOS EM SÉRIE'
                  when 17 then 'HONORÁRIOS'
                  when 18 then 'EXAMES'
                  when 19 then 'PACOTES'
                  when 20 then 'REVISÃO DE GLOSA'
                  when 21 then 'ODONTOLOGIA'
                  when 22 then 'MENSAGENS DE SISTEMA'
                  WHEN 23 then 'MENSAGENS RESERVADAS'
                  else
                      'OUTROS'
                END ds_grupo
          FROM dbaps.grupo_motivo_glosa
          WHERE cd_grupo_motivo_glosa <=23
        ) WHERE  ds_grupo_motivo_glosa <>  ds_grupo;

BEGIN
    --Limpando Tabela
    BEGIN
      DELETE FROM dbaps.ITEM_GRUPO_MOTIVO_GLOSA;
    END;

    -- INSERRINDO GRUPOS FALTANTES TABELA - Grupos e itens da tabela 38 padrão tiss 07/2021
    dbaps.prc_insere_grupo_mot_glosa( 1, 'ELEGIBILIDADE');
    dbaps.prc_insere_grupo_mot_glosa( 2, 'PROTOCOLO');
    dbaps.prc_insere_grupo_mot_glosa( 3, 'PRESTADOR');
    dbaps.prc_insere_grupo_mot_glosa( 4, 'GUIA');
    dbaps.prc_insere_grupo_mot_glosa( 5, 'AUTORIZAÇÃO/SOLICITAÇÃO');
    dbaps.prc_insere_grupo_mot_glosa( 6, 'DIAGNÓSTICO');
    dbaps.prc_insere_grupo_mot_glosa( 7, 'ATENDIMENTO');
    dbaps.prc_insere_grupo_mot_glosa( 8, 'REGRA DE VALORIZAÇÃO');
    dbaps.prc_insere_grupo_mot_glosa( 9, 'PROCEDIMENTO');
    dbaps.prc_insere_grupo_mot_glosa(10, 'DIÁRIA');
    dbaps.prc_insere_grupo_mot_glosa(11, 'MATERIAL');
    dbaps.prc_insere_grupo_mot_glosa(12, 'MEDICAMENTO');
    dbaps.prc_insere_grupo_mot_glosa(13, 'OPM');
    dbaps.prc_insere_grupo_mot_glosa(14, 'GASES MEDICINAIS');
    dbaps.prc_insere_grupo_mot_glosa(15, 'TAXAS E ALUGUÉIS');
    dbaps.prc_insere_grupo_mot_glosa(16, 'PROCEDIMENTOS EM SÉRIE');
    dbaps.prc_insere_grupo_mot_glosa(17, 'HONORÁRIOS');
    dbaps.prc_insere_grupo_mot_glosa(18, 'EXAMES');
    dbaps.prc_insere_grupo_mot_glosa(19, 'PACOTES');
    dbaps.prc_insere_grupo_mot_glosa(20, 'REVISÃO DE GLOSA');
    dbaps.prc_insere_grupo_mot_glosa(21, 'ODONTOLOGIA');
    dbaps.prc_insere_grupo_mot_glosa(22, 'MENSAGENS DE SISTEMA');
    dbaps.prc_insere_grupo_mot_glosa(23, 'MENSAGENS RESERVADAS');
    --inserindo itens de glosa para cada grupo
    --Grupo 1, 'ELEGIBILIDADE'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1001,1, 'NÚMERO DA CARTEIRA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1002,1, 'NÚMERO DO CARTÃO NACIONAL DE SAÚDE INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1003,1, 'A ADMISSÃO DO BENEFICIÁRIO NO PRESTADOR OCORREU ANTES DA INCLUSÃO DO BENEFICIÁRIO NA OPERADORA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1004,1, 'SOLICITAÇÃO ANTERIOR À INCLUSÃO DO BENEFICIÁRIO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1005,1, 'ATENDIMENTO ANTERIOR À INCLUSÃO DO BENEFICIÁRIO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1006,1, 'ATENDIMENTO APÓS O DESLIGAMENTO DO BENEFICIÁRIO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1007,1, 'ATENDIMENTO DENTRO DA CARÊNCIA DO BENEFICIÁRIO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1008,1, 'ASSINATURA DIVERGENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1009,1, 'BENEFICIÁRIO COM PAGAMENTO EM ABERTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1010,1, 'ASSINATURA DO TITULAR / RESPONSÁVEL INEXISTENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1011,1, 'IDENTIFICAÇÃO DO BENEFICIÁRIO NÃO CONSISTENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1012,1, 'SERVIÇO PROFISSIONAL HOSPITALAR NÃO É COBERTO PELO PLANO DO BENEFICIÁRIO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1013,1, 'CADASTRO DO BENEFICIÁRIO COM PROBLEMAS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1014,1, 'BENEFICIÁRIO COM DATA DE EXCLUSÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1015,1, 'IDADE DO BENEFICIÁRIO ACIMA IDADE LIMITE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1016,1, 'BENEFICIÁRIO COM ATENDIMENTO SUSPENSO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1017,1, 'DATA VALIDADE DA CARTEIRA VENCIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1018,1, 'EMPRESA DO BENEFICIÁRIO SUSPENSA / EXCLUÍDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1019,1, 'FAMÍLIA DO BENEFICIÁRIO COM ATENDIMENTO SUSPENSO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1020,1, 'VIA DE CARTÃO DO BENEFICIÁRIO CANCELADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1021,1, 'VIA DE CARTÃO DO BENEFICIÁRIO NÃO LIBERADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1022,1, 'VIA DE CARTÃO DO BENEFICIÁRIO NÃO COMPATÍVEL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1023,1, 'NOME DO TITULAR INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1024,1, 'PLANO NÃO EXISTENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1025,1, 'BENEFICIARIO NAO POSSUI COBERTURA PARA ASSISTENCIA ODONTOLOGICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1099,1, 'Outros');
    --  2, 'PROTOCOLO'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1101,2,'QUANTIDADE DE GUIAS INFORMADAS NO PROTOCOLO DIFERENTE DAS CADASTRADAS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1102,2,'PROTOCOLO É DE RE-APRESENTAÇÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1103,2,'PROTOCOLO NÃO É DE REAPRESENTAÇÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1104,2,'VALOR TOTAL DO PROTOCOLO DIFERENTE DO VALOR TOTAL DAS GUIAS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1199,2,'Outros');
    -- 3, 'PRESTADOR'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1201,3,'ATENDIMENTO FORA DA VIGÊNCIA DO CONTRATO COM O CREDENCIADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1202,3,'NÚMERO DO CNES INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1203,3,'CÓDIGO PRESTADOR INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1204,3,'ADMISSÃO ANTERIOR À INCLUSÃO DO CREDENCIADO NA REDE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1205,3,'ADMISSÃO APÓS O DESLIGAMENTO DO CREDENCIADO DA REDE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1206,3,'CPF / CNPJ INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1207,3,'CREDENCIADO NÃO PERTENCE À REDE CREDENCIADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1208,3,'SOLICITAÇÃO ANTERIOR À INCLUSÃO DO CREDENCIADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1209,3,'SOLICITAÇÃO APÓS O DESLIGAMENTO DO CREDENCIADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1210,3,'SOLICITANTE CREDENCIADO NÃO CADASTRADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1211,3,'ASSINATURA / CARIMBO DO CREDENCIADO INEXISTENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1212,3,'ATENDIMENTO / REFERÊNCIA FORA DA VIGÊNCIA DO CONTRATO DO PRESTADOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1213,3,'CBO-S (ESPECIALIDADE) INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1214,3,'CREDENCIADO NÃO HABILITADO A REALIZAR O PROCEDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1215,3,'CREDENCIADO FORA DA ABRANGÊNCIA GEOGRÁFICA DO PLANO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1216,3,'ESPECIALIDADE NÃO CADASTRADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1217,3,'ESPECIALIDADE NÃO CADASTRADA PARA O PRESTADOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1218,3,'CODIGO DE PRESTADOR IMCOMPATIVEL COM PROCEDIMENTO / EXAME COBRADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1299,3,'Outros');
    --4, 'GUIA'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1301,4,'TIPO GUIA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1302,4,'CÓDIGO TIPO GUIA PRINCIPAL E NÚMERO GUIAS INCOMPATÍVEIS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1303,4,'NÃO EXISTE O NÚMERO GUIA PRINCIPAL INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1304,4,'COBRANÇA EM GUIA INDEVIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1305,4,'ITEM PAGO EM OUTRA GUIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1306,4,'NÃO EXISTE NÚMERO GUIA PRINCIPAL E/OU CÓDIGO GUIA PRINCIPAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1307,4,'NÚMERO DA GUIA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1308,4,'GUIA JÁ APRESENTADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1309,4,'PROCEDIMENTO CONTRATADO NÃO ESTÁ DE ACORDO COM O TIPO DE GUIA UTILIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1310,4,'SERVIÇO DO TIPO CIRÚRGICO E INVASIVO. EQUIPE MÉDICA NÃO INFORMADA NA GUIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1311,4,'PRESTADOR EXECUTANTE NÃO INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1312,4,'PRESTADOR CONTRATADO NÃO INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1313,4,'GUIA COM RASURA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1314,4,'GUIA SEM ASSINATURA E/OU CARIMBO DO CREDENCIADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1315,4,'GUIA SEM DATA DO ATO CIRÚRGICO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1316,4,'GUIA COM LOCAL DE ATENDIMENTO PREENCHIDO INCORRETAMENTE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1317,4,'GUIA SEM DATA DO ATENDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1318,4,'GUIA COM CÓDIGO DE SERVIÇO  PREENCHIDO INCORRETAMENTE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1319,4,'GUIA SEM ASSINATURA DO ASSISTIDO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1320,4,'IDENTIFICAÇÃO DO ASSISTIDO INCOMPLETA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1321,4,'VALIDADE DA GUIA EXPIRADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1322,4,'COMPROVANTE PRESENCIAL OU GTO NAO ENVIADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1323,4,'DATA PREENCHIDA INCORRETAMENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1399,4,'Outros');
    --5, 'AUTORIZAÇÃO/SOLICITAÇÃO'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1401,5,'ACOMODAÇÃO NÃO AUTORIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1402,5,'PROCEDIMENTO NÃO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1403,5,'NÃO EXISTE INFORMAÇÃO SOBRE A SENHA DE AUTORIZAÇÃO DO PROCEDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1404,5,'NÃO EXISTE GUIA DE AUTORIZAÇÃO RELACIONADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1405,5,'DATA DE VALIDADE DA SENHA É ANTERIOR A DATA DO ATENDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1406,5,'NÚMERO DA SENHA INFORMADO DIFERENTE DO LIBERADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1407,5,'SERVIÇO SOLICITADO NÃO POSSUI COBERTURA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1408,5,'QUANTIDADE SERVIÇO SOLICITADA ACIMA DA AUTORIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1409,5,'QUANTIDADE SERVIÇO SOLICITADA ACIMA COBERTA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1410,5,'SERVIÇO SOLICITADO EM CARÊNCIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1411,5,'SOLICITANTE NÃO INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1412,5,'PROBLEMAS NO SISTEMA AUTORIZADOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1413,5,'ACOMODAÇÃO NÃO POSSUI COBERTURA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1414,5,'DATA DE VALIDADE DA SENHA EXPIRADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1415,5,'PROCEDIMENTO NÃO AUTORIZADO PARA O BENEFICIÁRIO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1416,5,'SOLICITANTE NÃO CADASTRADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1417,5,'SOLICITANTE NÃO HABILITADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1418,5,'SOLICITANTE SUSPENSO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1419,5,'SERVIÇO SOLICITADO JÁ AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1420,5,'SERVIÇO SOLICITADO FORA DA COBERTURA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1421,5,'SERVIÇO SOLICITADO É DE PRÉ-EXISTÊNCIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1422,5,'ESPECIALIDADE NÃO CADASTRADA PARA O SOLICITANTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1423,5,'QUANTIDADE SOLICITADA ACIMA DA QUANTIDADE PERMITIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1424,5,'QUANTIDADE AUTORIZADA ACIMA DA QUANTIDADE PERMITIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1425,5,'NECESSITA PRÉ-AUTORIZAÇÃO DA EMPRESA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1426,5,'NÃO AUTORIZADO PELA AUDITORIA MÉDICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1427,5,'NECESSIDADE DE AUDITORIA MÉDICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1428,5,'FALTA DE AUTORIZAÇÃO DA EMPRESA DE CONECTIVIDADE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1429,5,'CBO-S (ESPECIALIDADE) NÃO AUTORIZADO A REALIZAR O SERVIÇO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1430,5,'PROCEDIMENTO ODONTOLÓGICO NÃO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1431,5,'PROCEDIMENTO NÃO AUTORIZADO NA FACE SOLICITADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1432,5,'PROCEDIMENTO NÃO AUTORIZADO PARA DENTE/REGIÃO SOLICITADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1433,5,'PROCEDIMENTO NÃO AUTORIZADO, DENTE AUSENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1434,5,'COBRANCA DE CONTA DE CTI NEONATAL NA SENHA DO PARTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1435,5,'VIGENCIA DO ACORDO POSTERIOR A DATA DE REALIZACAO DO PROCEDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1436,5,'CANCELAMENTO DO ACORDO ANTERIOR A DATA DE REALIZACAO DO PROCEDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1437,5,'SENHA DE AUTORIZACAO CANCELADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1438,5,'PROCEDIMENTO SOLICITADO NAO AUTORIZADO POR NAO ATENDER A DIRETRIZ DE UTILIZACAO (DUT) DO ROL DE PROCEDIMENTOS E EVENTOS EM SAUDE DA ANS ');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1499,5,'Outros');
    --6, 'DIAGNÓSTICO'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1501,6,'TEMPO DE EVOLUÇÃO DA DOENÇA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1502,6,'TIPO DE DOENÇA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1503,6,'INDICADOR DE ACIDENTE INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1504,6,'CARÁTER DE INTERNAÇÃO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1505,6,'REGIME DA INTERNAÇÃO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1506,6,'TIPO DE INTERNAÇÃO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1507,6,'URGÊNCIA NÃO APLICÁVEL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1508,6,'CÓDIGO CID NÃO INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1509,6,'CÓDIGO CID INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1599,6,'Outros');
    -- 7, 'ATENDIMENTO'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1601,7,'REINCIDÊNCIA NO ATENDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1602,7,'TIPO DE ATENDIMENTO INVÁLIDO OU NÃO INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1603,7,'TIPO DE CONSULTA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1604,7,'TIPO DE SAÍDA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1605,7,'INTERVENÇÃO ANTERIOR A ADMISSÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1606,7,'FINAL DA INTERVENÇÃO ANTERIOR AO INÍCIO DA INTERVENÇÃO ');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1607,7,'ALTA HOSPITALAR ANTERIOR AO FINAL DA INTERVENÇÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1608,7,'ALTA ANTERIOR À DATA DE INTERNAÇÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1609,7,'MOTIVO SAÍDA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1610,7,'ÓBITO MULHER INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1611,7,'INTERVENÇÃO ANTERIOR A INTERNAÇÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1612,7,'SERVIÇO NÃO PODE SER REALIZADO NO LOCAL ESPECIFICADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1613,7,'CONSULTA NÃO AUTORIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1614,7,'SERVIÇO AMBULATORIAL NÃO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1615,7,'INTERNAÇÃO NÃO AUTORIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1699,7,'Outros');
    --8, 'REGRA DE VALORIZAÇÃO'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1701, 8,'COBRANÇA FORA DO PRAZO DE VALIDADE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1702, 8,'COBRANÇA DE PROCEDIMENTO EM DUPLICIDADE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1703, 8,'HORÁRIO DO ATENDIMENTO NÃO ESTÁ NA FAIXA DE URGÊNCIA/EMERGÊNCIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1704, 8,'VALOR COBRADO SUPERIOR AO ACORDADO EM PACOTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1705, 8,'VALOR APRESENTADO A MAIOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1706, 8,'VALOR APRESENTADO A MENOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1707, 8,'NÃO EXISTE INFORMAÇÃO SOBRE A TABELA QUE SERÁ UTILIZADA NA VALORAÇÃO. VERIFIQUE O CONTRATO DO PRESTADOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1708, 8,'NÃO EXISTE VALOR PARA O PROCEDIMENTO REALIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1709, 8,'FALTA PRESCRIÇÃO MÉDICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1710, 8,'FALTA VISTO DA ENFERMAGEM');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1711, 8,'PROCEDIMENTO PERTENCE A UM PACOTE ACORDADO E JÁ COBRADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1712, 8,'ASSINATURA DO MÉDICO RESPONSÁVEL PELO EXAME INEXISTENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1713, 8,'FATURAMENTO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1714, 8,'VALOR DO SERVIÇO SUPERIOR AO VALOR DE TABELA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1715, 8,'VALOR DO SERVIÇO INFERIOR AO VALOR DE TABELA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1716, 8,'PERCENTUAL DE REDUÇÃO/ACRÉSCIMO FORA DOS VALORES DEFINIDOS EM TABELA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1717, 8,'PAGO  CONFORME RELATORIO DE AUDITORIA EXTERNA - CONTA INICIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1718, 8,'REANALISE NEGADA, PAGO CONFORME RELATORIO AUDITORIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1719, 8,'REANALISE NEGADA, ANALISE CONFORME TABELA ACORDADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1720, 8,'LIBERADOS 150% DE VIDEO, SEM COBERTURA PARA ADICIONAL DE ACOMODACAO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1721, 8,'CODIGO COBRADO SUBSTITUIDO PELO CODIGO PAGO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1722, 8,'PAGO CONFORME NEGOCIACAO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1723, 8,'ADICIONAL DE URGENCIA NAO PREVISTO PARA ATENDIMENTO CLINICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1724, 8,'VISITA MEDICA COBRADA PELA EQUIPE CIRURGICA INCLUIDA NO PERIODO DE 10 DIAS APOS REALIZACAO DO PROCEDIMENTO CIRURGICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1725, 8,'VALOR PAGO A MAIOR REFERENTE A TAXA ADMINISTRATIVA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1726, 8,'VALOR APRESENTADO A MAIOR - PLANO INDIVIDUAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1727, 8,'PAGO VALOR COMPATIVEL COM O PROCEDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1728, 8,'COBRANCA DE MATERIAL INCLUSO NO PROCEDIMENTO / EXAME REALIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1729, 8,'COBRANCA DE MATERIAL COM VALOR ACIMA DO PERMITIDO PARA PROCEDIMENTO/EXAME REALIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1730, 8,'FILME INCLUSO NO EXAME REALIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1731, 8,'TAXA INCOMPATIVEL PARA ATENDIMENTO AMBULATORIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1732, 8,'QT COM DATA DE EVENTO DIVERGENTE DA LIBERADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1733, 8,'RECUPERACAO DE VALORES POR PAGAMENTO INDEVIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1734, 8,'COBRADO CONTA ABERTA, PAGO O PACOTE CONFORME NEGOCIACAO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1735, 8,'COBRANCA DE PACOTE NAO NEGOCIADO COM O PRESTADOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1736, 8,'CONTA AGUARDANDO NEGOCIACAO PARA PAGAMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1737, 8,'DIFERENCA DEVE SER COBRADA DO BENEFICIARIO PELO PRESTADOR COMO FRANQUIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1738, 8,'DOCUMENTO FISCAL NAO ENVIADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1739, 8,'DUPLICIDADE DE CONTA DEVIDO A PERIODO COBRADO JA EFETUADO EM OUTRA PARCIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1740, 8,'ESTORNO DO VALOR DE PROCEDIMENTO PAGO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1741, 8,'HONORARIO OU PROCEDIMENTO JA PAGO A OUTRO PRESTADOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1742, 8,'HONORARIO OU PROCEDIMENTO JA PAGO POR REEMBOLSO AO BENEFICIARIO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1743, 8,'NAO HA NEGOCIACAO PARA COBRANCA DO KIT, DISCRIMINAR POR ITENS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1744, 8,'NEGOCIACAO DIFERENCIADA DEVIDO A LIMINAR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1745, 8,'PAGAMENTO DA EQUIPE CONFORME RELATORIO DO CIRURGIAO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1746, 8,'PERCENTUAL DE ACRESCIMO DIFERENTE DO NEGOCIADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1747, 8,'PLANO DO BENEFICIARIO E O TIPO DE ACOMODACAO NAO PERMITEM ACRESCIMO DE HONORARIOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1748, 8,'PROCEDIMENTO NAO CARACTERIZA URGENCIA/EMERGENCIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1749, 8,'RELATORIO DE AUDITORIA NAO ENVIADO NA CONTA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1799, 8,'Outros');
    --9, 'PROCEDIMENTO'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1801, 9,'PROCEDIMENTO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1802, 9,'PROCEDIMENTO INCOMPATÍVEL COM O SEXO DO BENEFICIÁRIO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1803, 9,'IDADE DO BENEFICIÁRIO INCOMPATÍVEL COM O PROCEDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1804, 9,'NÚMERO DE DIAS LIBERADOS / SESSÕES AUTORIZADAS NÃO INFORMADAS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1805, 9,'VALOR TOTAL DO PROCEDIMENTO DIFERENTE DO VALOR PROCESSADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1806, 9,'QUANTIDADE DE PROCEDIMENTO DEVE SER MAIOR QUE ZERO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1807, 9,'PROCEDIMENTOS MÉDICOS DUPLICADOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1808, 9,'PROCEDIMENTO NÃO CONFORME COM CID');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1809, 9,'COBRANÇA DE PROCEDIMENTO NÃO EXECUTADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1810, 9,'COBRANÇA DE PROCEDIMENTO NÃO SOLICITADO PELO MÉDICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1811, 9,'PROCEDIMENTO SEM REGISTRO DE EXECUÇÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1812, 9,'COBRANÇA DE PROCEDIMENTO NÃO CORRELACIONADO AO RELATÓRIO ESPECÍFICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1813, 9,'COBRANÇA DE PROCEDIMENTO SEM JUSTIFICATIVA PARA REALIZAÇÃO OU COM JUSTIFICATIVA INSUFICIENTE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1814, 9,'COBRANÇA DE PROCEDIMENTO COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1815, 9,'PROCEDIMENTO NÃO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1816, 9,'COBRANÇA DE PROCEDIMENTO EM QUANTIDADE INCOMPATÍVEL COM O PROCEDIMENTO/EVOLUÇÃO CLÍNICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1817, 9,'COBRANÇA DE PROCEDIMENTO INCLUSO NO PROCEDIMENTO PRINCIPAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1818, 9,'COBRANÇA DE PROCEDIMENTO QUE EXIGE AUTORIZAÇÃO PRÉVIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1819, 9,'COBRANÇA DE PROCEDIMENTO COM HISTÓRIA CLÍNICA/HIPÓTESE DIAGNÓSTICA NÃO COMPATÍVEL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1820, 9,'COBRANÇA DE PROCEDIMENTO EM QUANTIDADE ACIMA DA MÁXIMA PERMITIDA/AUTORIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1821, 9,'COBRANÇA DE PROCEDIMENTO NÃO COMPATÍVEL COM A IDADE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1822, 9,'COBRANÇA DE PROCEDIMENTO COM AUSÊNCIA DE RESULTADO OU LAUDO TÉCNICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1823, 9,'PROCEDIMENTO REALIZADO PELO MESMO PROFISSIONAL, NA MESMA ESPECIALIDADE, NO PRAZO INFERIOR AO ESTIPULADO SEM JUSTIFICATIVA ADEQUADA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1824, 9,'PROCEDIMENTO COBRADO NÃO CORRESPONDE AO EXAME EXECUTADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1825, 9,'COBRANÇA DE PROCEDIMENTO AMBULATORIAL COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1826, 9,'VIAS DE ACESSO DOS PROCEDIMENTOS COBRADOS NAO ESTAO PREVISTAS NA LISTAGEM DE PROCEDIMENTOS MULTIPLOS.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1827, 9,'COBRANCA DE OUTRO PROCEDIMENTO EM OUTRA GUIA, NA MESMA DATA, PELO MESMO PROFISSIONAL COM MESMO GRAU DE PARTICIPACAO - LIBERADO VALOR REFERENTE A VIA DE ACESSO DO PROCEDIMENTO SECUNDARIO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1828, 9,'ADICIONAL DE URGENCIA NAO PREVISTO PARA PROCEDIMENTO CIRURGICO ELETIVO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1829, 9,'ADICIONAL DE VIDEO NAO PREVISTO PARA O PROCEDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1830, 9,'COBRANCA DE PROCEDIMENTO SEM INFORMACAO DAS DATAS DE ATENDIMENTO-VISITA, PLANTAO, INTENSIVISTA, AVALIACAO ENTERAL/PARENTERAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1831, 9,'LAUDO DO EXAME ENVIADO NAO JUSTIFICA A COBRANCA DO PROCEDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1832, 9,'PROCEDIMENTO NAO PERMITE COBRANCA DE AUXILIAR DE ANESTESISTA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1833, 9,'PROCEDIMENTO COBRADO NAO PERMITE ACRESCIMO DE ACOMODACAO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1834, 9,'PORTE ANESTESICO COBRADO INCOMPATIVEL COM O PORTE DO PROCEDIMENTO REALIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1835, 9,'ANALGESIA POR DIA SUBSEQUENTE - NAO JUSTIFICADA EM RELATORIO MEDICO, PARA O PROCEDIMENTO REALIZADO E/OU DATA DO ATENDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1836, 9,'ANALGESIA POR DIA SUBSEQUENTE - INCOMPATIVEL COM A VIA DE ADMINISTRACAO DO MEDICAMENTO - VO OU IV PERIFERICA - SENDO LIBERADA VISITA HOSPITALAR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1837, 9,'NAO CABE PAGAMENTO DO HONORARIO INTEGRAL POR SER VIA DE ACESSO CIRURGICO DIFERENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1838, 9,'GRAU DE PARTICIPACAO INFORMADO INCOMPATIVEL COM EVENTO COBRADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1839, 9,'NECESSARIO ENVIO DO RESULTADO DO EXAME ANATOMO PATOLOGICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1840, 9,'PROCEDIMENTO EXECUTADO ANTES DA AUTORIZACAO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1899, 9,'Outros');
    --10, 'DIÁRIA'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1901,10,'ACOMODAÇÃO INVÁLIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1902,10,'ACOMODAÇÃO INFORMADA NÃO ESTÁ DE ACORDO COM ACOMODAÇÃO CONTRATADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1903,10,'PERMANÊNCIA HOSPITALAR INCOMPATÍVEL COM A EVOLUÇÃO CLÍNICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1904,10,'PERMANÊNCIA HOSPITALAR INCOMPATÍVEL COM O PROCEDIMENTO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1905,10,'QUANTIDADE DE DIÁRIAS DEVE SER MAIOR QUE ZERO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1906,10,'ACOMODAÇÃO NÃO INFORMADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1907,10,'QUANTIDADE UTI NÃO PREVISTA PARA PROCEDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1908,10,'USUÁRIO NÃO POSSUI COBERTURA DE UTI');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1909,10,'ACOMODAÇÃO NÃO AUTORIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1910,10,'COBRANÇA DE DIÁRIAS EM LOCAIS DE ACOMODAÇÕES DIFERENTES, NO MESMO DIA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1911,10,'PERMANÊNCIA HOSPITALAR PARA INVESTIGAÇÃO INJUSTIFICADA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1912,10,'EVOLUÇÃO CLÍNICA NÃO COMPATÍVEL COM A PERMANÊNCIA EM UTI.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1913,10,'CÓDIGO DE DIÁRIA INCOMPATÍVEL COM O LOCAL DE ATENDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1914,10,'COBRANÇA DE DIÁRIA EM QUANTIDADE INCOMPATÍVEL COM A PERMANÊNCIA HOSPITALAR.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1915,10,'MUDANÇA DE ACOMODAÇÃO SEM COMUNICAÇÃO AO PACIENTE, FAMILIAR OU ACOMPANHANTE, OU SEM SOLICITAÇÃO DESTES.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1916,10,'COBRANÇA DE DIÁRIAS DE UTI INCOMPATÍVEL COM DIAGNÓSTICO E EVOLUÇÃO CLÍNICA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1917,10,'FALTA PRORROGACAO PARA QUANTIDADE DE DIARIAS COBRADAS.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1918,10,'PLANO DO BENEFICIARIO NAO CONTEMPLA DIARIA DE ACOMPANHANTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(1999,10,'Outros');
    --11, 'MATERIAL'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2001,11,'MATERIAL INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2002,11,'MATERIAL SEM COBERTURA PARA ATENDIMENTO AMBULATORIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2003,11,'MATERIAL NÃO ESPECIFICADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2004,11,'MATERIAL SEM NOTA FISCAL DO FORNECEDOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2005,11,'QUANTIDADE DE MATERIAL DEVE SER MAIOR QUE ZERO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2006,11,'MATERIAL INFORMADO NÃO COBERTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2007,11,'COBRANÇA DE MATERIAL EM QUANTIDADE INCOMPATÍVEL COM A PERMANÊNCIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2008,11,'COBRANÇA DE MATERIAL  EM QUANTIDADES INCOMPATÍVEIS COM O PROCEDIMENTO REALIZADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2009,11,'QUANTIDADE DE MATERIAL SUPERIOR A QUANTIDADE COBERTA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2010,11,'COBRANÇA DE MATERIAIS INCLUSOS NAS TAXAS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2011,11,'COBRANÇA DE MATERIAL INCLUSO NO PACOTE NEGOCIADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2012,11,'COBRANÇA DE MATERIAL INCOMPATÍVEL COM O RELATÓRIO TÉCNICO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2013,11,'COBRANÇA DE MATERIAL EM PERMANÊNCIA HOSPITALAR NÃO AUTORIZADA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2014,11,'COBRANÇA DE MATERIAL NÃO UTILIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2015,11,'MATERIAL NAO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2099,11,'Outros');
    --12, 'MEDICAMENTO'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2101,12,'MEDICAMENTO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2102,12,'MEDICAMENTO SEM COBERTURA PARA ATENDIMENTO AMBULATORIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2103,12,'MEDICAMENTO NÃO ESPECIFICADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2104,12,'MEDICAMENTO SEM NOTA FISCAL DO FORNECEDOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2105,12,'QUANTIDADE DE MEDICAMENTOS DEVE SER MAIOR QUE ZERO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2106,12,'MEDICAMENTO INFORMADO NÃO COBERTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2107,12,'COBRANÇA DE MEDICAMENTO EM QUANTIDADE INCOMPATÍVEL COM A PERMANÊNCIA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2108,12,'COBRANÇA DE MEDICAMENTO EM QUANTIDADES INCOMPATÍVEIS COM O PROCEDIMENTO REALIZADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2109,12,'QUANTIDADE DE MEDICAMENTO SUPERIOR A QUANTIDADE COBERTA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2110,12,'COBRANÇA DE MEDICAMENTO INCLUSOS NAS TAXAS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2111,12,'COBRANÇA DE MEDICAMENTO INCLUSO NO PACOTE NEGOCIADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2112,12,'COBRANÇA DE MEDICAMENTO INCOMPATÍVEL COM O RELATÓRIO TÉCNICO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2113,12,'COBRANÇA DE MEDICAMENTO EM PERMANÊNCIA HOSPITALAR NÃO AUTORIZADA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2114,12,'COBRANÇA DE MEDICAMENTO NÃO UTILIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2115,12,'MEDICAMENTO NAO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2199,12,'Outros');
    --13 - 13, 'OPM'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2201,13,'OPM INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2202,13,'OPM SEM COBERTURA PARA ATENDIMENTO AMBULATORIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2203,13,'OPM SEM NOTA FISCAL DO FORNECEDOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2204,13,'QUANTIDADE DE OPM DEVE SER MAIOR QUE ZERO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2205,13,'OPM INFORMADO NÃO COBERTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2206,13,'OPM INFORMADO NÃO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2207,13,'COBRANÇA DE OPM NÃO UTILIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2208,13,'COBRANÇA DE OPM NO ITEM MATERIAL E MEDICAMENTOS.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2209,13,'COBRANÇA DE OPM EM DESACORDO COM RELATÓRIO TÉCNIC');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2210,13,'COBRANÇA DE OPM EM QUANTIDADE INCOMPATÍVEL COM O PROCEDIMENTO REALIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2211,13,'COBRANÇA DE OPM INCLUSA NO PACOTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2212,13,'OPME EM DESACORDO COM OS CRITERIOS TECNICOS ADOTADOS PELA OPERADORA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2213,13,'OPME PAGO A FORNECEDOR TERCEIRIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2299,13,'Outros');
    -- 14, 'GASES MEDICINAIS'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2301,14,'GASES MEDICINAIS INVÁLIDOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2302,14,'COBRANÇA DE OXIGENOTERAPIA SEM PRESCRIÇÃO MÉDICA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2303,14,'COBRANÇA DE OXIGENOTERAPIA COM QUANTITATIVO DE USO EM DIVERGÊNCIA/PAGO VALOR CORRIGIDO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2304,14,'COBRANÇA DE OXIGÊNIO INCLUSO NA TAXA DE NEBULIZAÇÃO ESPECIFICADA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2305,14,'COBRANÇA DE OXIGENOTERAPIA EM USO PROLONGADO  SEM JUSTIFICATIVA DE USO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2306,14,'COBRANÇA DE OXIGENOTERAPIA SEM REGISTRO DE CONTROLE DE USO (ENTRADA E SAÍDA).');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2307,14,'COBRANÇA DE GASES EM QUANTIDADE SUPERIOR AO PERÍODO DE PERMANÊNCIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2308,14,'COBRANÇA DE CO2 NAS CIRURGIAS VIDEOLAPAROSCÓPICAS DURANTE TODA A REALIZAÇÃO DO PROCEDIMENTO (INÍCIO AO FIM).');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2309,14,'COBRANÇA DE AR COMPRIMIDO SEM REGISTRO NO BOLETIM ANESTÉSICO E DURAÇÃO DE USO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2310,14,'COBRANÇA DE GASES INCOMPATÍVEL COM O UTILIZADO/ PRESCRITO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2399,14,'Outros');
    --15, 'TAXAS E ALUGUÉIS'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2401,15,'TAXA / ALUGUEL INVÁLIDO                                                                                                                                                                       ');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2402,15,'COBRANÇA DE TAXA POR USO DE EQUIPAMENTO INCOMPATÍVEL COM O PROCEDIMENTO REALIZADO/USO PREVISTO NO PROCEDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2403,15,'COBRANÇA DE TAXA DE USO DE BOMBA DE INFUSÃO EM PACIENTE INTERNADO NA UTI');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2404,15,'COBRANÇA DE OUTRAS TAXAS ASSOCIADAS/INCLUSAS NA COBRANÇA DA TAXA DE SALA PREVISTA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2405,15,'COBRANÇA DE MAIS DE UMA TAXA DE SALA DE CIRURGIA, POR CONTA DO NÚMERO DE PROCEDIMENTOS REALIZADOS NO MESMO TEMPO CIRÚRGICO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2406,15,'COBRANÇA INDEVIDA DE TAXA DE SALA POR ADMINISTRAÇÃO DE MEDICAMENTOS.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2407,15,'COBRANÇA DE TAXAS, DE SERVIÇOS REALIZADOS EM AMBIENTES INCOMPATÍVEIS COM O USO DE EQUIPAMENTOS.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2408,15,'COBRANÇA DE TAXAS EM QUANTIDADE SUPERIOR AO TEMPO DE PERMANÊNCIA HOSPITALAR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2409,15,'COBRANÇA DE TAXA DE OBSERVAÇÃO EM PRONTO SOCORRO COM PERMANÊNCIA MENOR QUE O PERÍODO ESTIPULADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2410,15,'COBRANÇA DE TAXA DE OBSERVAÇÃO EM PRONTO SOCORRO SEM O REGISTRO DA PERMANÊNCIA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2411,15,'COBRANÇA DE TAXA DE SALA DE PRONTO SOCORRO, PARA APLICAÇÃO DE MEDICAMENTOS.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2412,15,'COBRANÇA DE TAXA DE RECUPERAÇÃO ANESTÉSICA NÃO JUSTIFICADA PARA O PROCEDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2413,15,'COBRANÇA DE TAXA INCLUSA NO PACOTE NEGOCIADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2414,15,'COBRANÇA DE TAXA DE EQUIPAMENTO EM CONCOMITÂNCIA COM A COBRANÇA DE TAXA PARA O PROCEDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2415,15,'TAXA EXIGE INFORMAÇÃO DO VALOR NA GUIA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2416,15,'COBRANÇA DE TAXA DE RECUPERAÇÃO ANESTÉSICA PARA PACIENTES COM PÓS-OPERATÓRIO IMEDIATO REALIZADO NA UTI/CTI.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2417,15,'COBRANÇA DE TAXA DE RECUPERAÇÃO ANESTÉSICA SEM A PRESENÇA DO ANESTESISTA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2418,15,'COBRANÇA DE TAXA DE SALA INCOMPATÍVEL COM O PROCEDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2419,15,'COBRANÇA DE TAXA DE OBSERVAÇÃO PARA ATENDIMENTO QUE GEROU UMA INTERNAÇÃO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2420,15,'COBRANÇA DE TAXA DE SALA CIRÚRGICA COM PORTE ANESTÉSICO DIFERENTE DO PROCEDIMENTO AUTORIZADO/REALIZADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2421,15,'COBRANÇA DE TAXA EM QUANTIDADE INCORRETA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2422,15,'COBRANÇA DE TAXA POR USO DE EQUIPAMENTO DE USO OBRIGATÓRIO NA SALA DE CIRURGIA, CUJA TAXA DE SALA CIRÚRGICA JÁ INCLUI SEU USO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2423,15,'COBRANÇA DE TAXA DE EQUIPAMENTOS DE USO OBRIGATÓRIO NO LOCAL DE ATENDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2424,15,'COBRANÇA DE TAXA DE OBSERVAÇÃO PARA ATENDIMENTO QUE GEROU UMA INTERNAÇÃO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2499,15,'Outros');
    -- 16 'PROCEDIMENTOS EM SÉRIE'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2501,16,'PROCEDIMENTO EM SÉRIE INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2502,16,'COBRANÇA DE DUAS AVALIAÇÕES FISIOTERÁPICAS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2503,16,'COBRANÇA DE PSICOTERAPIA INDIVIDUAL, QUANDO O APLICADO É A COBRANÇA DE PSICOTERAPIA EM GRUP');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2504,16,'QUANTIDADE DE SESSÕES COBRADAS NÃO CONDIZEM COM AS ASSINATURAS NO CONTROLE DE TRATAMENTO SERIADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2505,16,'O CÓDIGO COBRADO É DIFERENTE DO CÓDIGO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2506,16,'A QUANTIDADE DE SESSÕES  COBRADAS É DIFERENTE DA QUANTIDADE AUTORIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2507,16,'O CÓDIGO AUTORIZADO ESTÁ INCOMPATÍVEL COM A PRESCRIÇÃO MÉDICA SOLICITADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2508,16,'COBRANÇA DE SESSÕES  SEM O DEVIDO PLANO DE TRATAMENTO E, OU, COM O PRAZO DE PAGAMENTO EXPIRADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2509,16,'COBRANÇA DO PROCEDIMENTO SERIADO INCOMPATÍVEL COM O QUADRO CLÍNICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2510,16,'COBRANÇA DO PROCEDIMENTO SERIADO EM NÚMERO DE SESSÕES ACIMA DA QUANTIDADE ESTABELECIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2511,16,'AUSÊNCIA DE EVOLUÇÃO NO PRONTUÁRIO MÉDICO DO TRATAMENTO SERIADO REALIZADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2512,16,'COBRANÇA DE SESSÕES DE FISIOTERAPIA EM DESACORDO COM AS EVOLUÇÕES DO PRONTUÁRIO MÉDICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2513,16,'COBRANÇA DE TRATAMENTO SERIADO SEM JUSTIFICATIVA CLÍNICA/TÉCNICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2514,16,'SERVIÇO NÃO CONTRATADO PARA O PRESTADOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2515,16,'LOCAL DE ATENDIMENTO INADEQUADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2516,16,'QUANTIDADE COBRADA DIFERENTE DA REALIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2599,16,'Outros');
    --17, 'HONORÁRIOS'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2601,17,'CODIFICAÇÃO INCORRETA/INADEQUADA DO PROCEDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2602,17,'COBRANÇA DE HONORÁRIO INCLUSO NO PROCEDIMENTO PRINCIPAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2603,17,'COBRANÇA DE HONORÁRIO SEM REGISTRO DA EFETIVA PARTICIPAÇÃO DO PROFISSIONAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2604,17,'PROCEDIMENTO PRINCIPAL NÃO REQUER EQUIPE MÉDICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2605,17,'NÃO CABE PAGAMENTO DO HONORÁRIO INTEGRAL POR SER A MESMA VIA DE ACESSO CIRÚRGICO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2606,17,'COBRANÇA DO HONORÁRIO EM LOCAL DE ATENDIMENTO INCORRETO (INEXISTENTE).');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2607,17,'COBRANÇA DE HONORÁRIOS EM DUPLICIDADE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2608,17,'COBRANÇA DE CONSULTA INDEVIDA, QUANDO O PROCEDIMENTO PRINCIPAL JÁ ESTÁ SENDO REMUNERADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2609,17,'LOCAL DE ATENDIMENTO NÃO INFORMADO.');
    --Itens existente na base MVDSV e que não constam na planilha
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2610,17,'GRAU DE PARTICIPACAO DE AUXILIAR INCOMPATIVEL COM PROCEDIMENTO COBRADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2611,17,'COBRANCA DE ESPECIALISTA NAO JUSTIFICADA NO EVENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2612,17,'COBRANCA INDEVIDA DE EQUIPE "STAND-BY", JA QUE ANGIOPLASTIA SEGUIDA DE CIRURGIA CARDIACA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2613,17,'HONORARIO MEDICO DO ANESTESISTA JA LIBERADO NO PROCEDIMENTO CIRURGICO, POIS "ANALGESIA POR DIA SUBSEQUENTE" COBRADA NA MESMA DATA DO EVENTO CIRURGICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2614,17,'COBRANCA DE CADA PARTICIPANTE DA EQUIPE DEVE SER FEITA EM GUIAS DIFERENTES');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2615,17,'LOCAL DE ATENDIMENTO INADEQUADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2616,17,'QUANTIDADE COBRADA DIFERENTE DA REALIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2699,17,'Outros');
    --18, 'EXAMES'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2701,18,'PROCEDIMENTO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2702,18,'COBRANÇA DE EXAME NÃO SOLICITADO PELO MÉDICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2703,18,'EXAME SEM REGISTRO DE EXECUÇÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2704,18,'COBRANÇA DE EXAME NÃO CORRELACIONADO AO RELATÓRIO ESPECÍFICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2705,18,'COBRANÇA DE PROCEDIMENTO/EXAME SEM JUSTIFICATIVA PARA REALIZAÇÃO OU COM JUSTIFICATIVA INSUFICIENTE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2706,18,'COBRANÇA DE PROCEDIMENTO/EXAME COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2707,18,'EXAME NÃO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2708,18,'COBRANÇA DE EXAME EM QUANTIDADE INCOMPATÍVEL COM O PROCEDIMENTO/EVOLUÇÃO CLÍNICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2709,18,'COBRANÇA DE PROCEDIMENTO INCLUSO NO PROCEDIMENTO PRINCIPAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2710,18,'COBRANÇA DE EXAME QUE EXIGE AUTORIZAÇÃO PRÉVIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2711,18,'COBRANÇA DE EXAME COM HISTÓRIA CLÍNICA/HIPÓTESE DIAGNÓSTICA NÃO COMPATÍVEL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2712,18,'COBRANÇA DE EXAME EM QUANTIDADE ACIMA DA MÁXIMA PERMITIDA/AUTORIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2713,18,'COBRANÇA DE EXAME NÃO COMPATÍVEL COM A IDADE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2714,18,'COBRANÇA DE EXAME COM AUSÊNCIA DE RESULTADO OU LAUDO TÉCNICO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2715,18,'EXAME REALIZADO PELO MESMO PROFISSIONAL, NA MESMA  ESPECIALIDADE, NO PRAZO INFERIOR AO ESTIPULADO SEM JUSTIFICATIVA ADEQUADA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2716,18,'EXAME COBRADO NÃO CORRESPONDE AO EXAME  EXECUTADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2717,18,'COBRANÇA DE EXAME AMBULATORIAL COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2718,18,'EXAMES NÃO JUSTIFICAM CARÁTER DE URGÊNCIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2799,18,'Outros');
    --19, 'PACOTES'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2801,19,'PACOTE INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2802,19,'PACOTE INCOMPATÍVEL COM O SEXO DO BENEFICIÁRIO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2803,19,'IDADE DO BENEFICIÁRIO INCOMPATÍVEL COM O PACOTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2804,19,'VALOR TOTAL DO PACOTE DIFERENTE DO VALOR PROCESSADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2805,19,'VALOR DO PACOTE SUPERIOR AO VALOR DOS ITENS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2806,19,'COBRANÇA DE PACOTE NÃO EXECUTADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2807,19,'COBRANÇA DE PACOTE NÃO SOLICITADO PELO MÉDICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2808,19,'PACOTE SEM REGISTRO DE EXECUÇÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2809,19,'COBRANÇA DE PACOTE NÃO CORRELACIONADO AO RELATÓRIO ESPECÍFICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2810,19,'COBRANÇA DE PACOTE SEM JUSTIFICATIVA PARA REALIZAÇÃO OU COM JUSTIFICATIVA INSUFICIENTE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2811,19,'COBRANÇA DE PACOTE COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2812,19,'PACOTE NÃO AUTORIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2813,19,'COBRANÇA DE PACOTE EM QUANTIDADE INCOMPATÍVEL COM O PROCEDIMENTO/EVOLUÇÃO CLÍNICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2814,19,'ITENS DE COMPOSIÇÃO DO PACOTE NÃO REALIZADOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2815,19,'COBRANÇA DO PACOTE EXIGE AUTORIZAÇÃO PRÉVIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2816,19,'COBRANÇA DE PACOTE COM HISTÓRIA CLÍNICA/HIPÓTESE DIAGNÓSTICA NÃO COMPATÍVEL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2817,19,'COBRANÇA DE PACOTE EM QUANTIDADE ACIMA DA MÁXIMA PERMITIDA/AUTORIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2818,19,'COBRANÇA DE PACOTE NÃO COMPATÍVEL COM A IDADE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2819,19,'COBRANÇA DE PACOTE COM AUSÊNCIA DE RESULTADO OU LAUDO TÉCNICO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2820,19,'PACOTE REALIZADO PELO MESMO PROFISSIONAL, NA MESMA ESPECIALIDADE, NO PRAZO INFERIOR AO ESTIPULADO SEM JUSTIFICATIVA ADEQUADA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2821,19,'PACOTE COBRADO NÃO CORRESPONDE AO EXAME EXECUTADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2822,19,'COBRANÇA DE PACOTE AMBULATORIAL COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2899,19,'Outros');
    --20, 'REVISÃO DE GLOSA'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2901,20,'REVISÃO DE GLOSA INVÁLIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2902,20,'GLOSA MANTIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2903,20,'PEDIDO DE REVISÃO SEM JUSTIFICATIVA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2904,20,'MAIS DE UM RECURSO DE GLOSA PARA A MESMA GUIA/PROTOCOLO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2905,20,'A GUIA NÃO É DE REVISÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2906,20,'NÚMERO DA GUIA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2907,20,'PRAZO DE 180 DIAS ULTRAPASSADO PARA SOLICITACAO DE REANALISE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2908,20,'SOLICITACAO DE REANALISE EFETUADA DE FORMA INCORRETA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2909,20,'PRAZO PARA SOLICITACAO DE RECURSO DE GLOSA PRESCRITO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(2999,20,'Outros');
    -- 21, 'ODONTOLOGIA'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3001,21,'PROCEDIMENTO ODONTOLÓGICO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3002,21,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO QUE EXIGE AUTORIZAÇÃO PRÉVIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3003,21,'IDADE DO BENEFICIÁRIO INCOMPATÍVEL COM O PROCEDIMENTO ODONTOLÓGICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3004,21,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO EM QUANTIDADE ACIMA DA MÁXIMA PERMITIDA/AUTORIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3005,21,'VALOR TOTAL DO PROCEDIMENTO DIFERENTE DO VALOR PROCESSADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3006,21,'QUANTIDADE DE  PROCEDIMENTO DEVE SER MAIOR  QUE ZERO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3007,21,'PROCEDIMENTOS ODONTOLÓGICOS DUPLICADOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3008,21,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO INCLUSO NO PROCEDIMENTO PRINCIPAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3009,21,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO NÃO EXECUTADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3010,21,'COBRANÇA DE PROCEDIMENTO NÃO SOLICITADO PELO CIRURGIÃO-DENTISTA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3011,21,'PROCEDIMENTO ODONTOLÓGICO SEM REGISTRO DE EXECUÇÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3012,21,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO NÃO CORRELACIONADO AO RELATÓRIO ESPECÍFICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3013,21,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO SEM JUSTIFICATIVA PARA REALIZAÇÃO OU COM JUSTIFICATIVA INSUFICIENTE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3014,21,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO COM DATA DE AUTORIZAÇÃO POSTERIOR À DO ATENDIMENTO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3015,21,'COBRANÇA DE PROCEDIMENTO ODONTOLÓGICO COM AUSÊNCIA DE RESULTADO OU LAUDO TÉCNICO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3016,21,'PROCEDIMENTO ODONTOLÓGICO REALIZADO PELO MESMO PROFISSIONAL, NA MESMA ESPECIALIDADE, NO PRAZO INFERIOR AO ESTIPULADO SEM JUSTIFICATIVA ADEQUADA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3017,21,'PROCEDIMENTO COBRADO NÃO CORRESPONDE A PERÍCIA (ESPECIFICAR).');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3018,21,'EVENTO GLOSADO POR AUDITORIA (ESPECIFICAR)');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3019,21,'EVENTO SOB ANÁLISE TÉCNICA, AGUARDANDO LIBERAÇÃO DE CONFIRMAÇÃO PARA POSTERIOR PAGAMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3020,21,'CONFORME DOCUMENTAÇÃO RADIOGRÁFICA ENVIADA, EVENTO REALIZADO INADEQUADAMENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3021,21,'FALHA EM INFORMAÇÃO DE DADOS DE ARCADAS/HEMIARCOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3022,21,'FALHA EM INFORMAÇÃO DE DADOS DE DENTE INICIAL E/OU FINAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3023,21,'FALHA EM INFORMAÇÃO DE DADOS DE FACES DOS DENTES');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3024,21,'EVENTO SÓ POSSÍVEL EM DENTES DECÍDUOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3025,21,'EVENTO SÓ POSSÍVEL EM DENTES PERMANENTES');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3026,21,'ERRO NAS INFORMAÇÕES DE ORDEM DOS DENTES INICIAL E FINAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3027,21,'DESACORDO ENTRE O TIPO DE DENTE E O NÚMERO DE CANAIS SOLICITADOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3028,21,'EVENTO RESTRITO À ESPECIALISTAS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3029,21,'EVENTO NÃO INDICADO PELA AUDITORIA INICIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3030,21,'AUDITORIA FINAL CONSTA QUE A RESTAURAÇÃO FOI REALIZADA EM OUTRO MATERIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3031,21,'RX FORA DOS PADRÕES TÉCNICOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3032,21,'INTERVALO DA ÚLTIMA MPP INFERIOR A TRÊS MESES');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3033,21,'INTERVALO DA ÚLTIMA MPP INFERIOR A QUATRO MESES');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3034,21,'JUSTIFICATIVA TECNICAMENTE NÃO SATISFATÓRIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3035,21,'PACIENTE EM TRATAMENTO COM O MESMO PROFISSIONAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3036,21,'PACIENTE EM TRATAMENTO COM OUTRO PROFISSIONAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3037,21,'PROCEDIMENTO COBRADO NÃO É IGUAL AO EXECUTADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3038,21,'RX INICIAL INCONGRUENTE COM O RX FINAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3039,21,'RX NÃO CORRESPONDE AO PROCEDIMENTO COBRADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3040,21,'GLOSA TÉCNICA (ESPECIFICAR DETALHADAMENTE)');
    --Itens existente na base MVDSV e que não constam na planilha
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3041,21,'AGUARDANDO DOCUMENTACAO DE ORTODONTIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3042,21,'APOS ANALISE DA RADIOGRAFIA INICIAL VERIFICOU-SE EXODONTIA DE INCLUSO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3043,21,'APOS ANALISE DA RADIOGRAFIA INICIAL VERIFICOU-SE EXODONTIA DE SEMI-INCLUSO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3044,21,'APOS ANALISE DA RADIOGRAFIA INICIAL VERIFICOU-SE EXODONTIA SIMPLES');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3045,21,'APOS ANALISE DA RADIOGRAFIA INICIAL, VERIFICOU-SE EXODONTIA DE FRAGMENTO RADICULAR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3046,21,'AUDITORIA FINAL CONSTA QUE O PROCEDIMENTO FOI REALIZADO COM OUTRO MATERIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3047,21,'AUSENCIA DE IMAGEM/FOTO/RADIOGRAFIA/ DIAGNOSTICO POS PROCEDIMENTO ODONTOLOGICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3048,21,'CANCELAMENTO DO PROCEDIMENTO ODONTOLOGICO POR SOLICITACAO DO BENEFICIARIO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3049,21,'CANCELAMENTO DO PROCEDIMENTO ODONTOLOGICO POR SOLICITACAO DO PRESTADOR.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3050,21,'COBRANCA DE URGENCIA/EMERGENCIA NA VIGENCIA DO TRATAMENTO ODONTOLOGICO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3051,21,'DOCUMENTACAO EM ANALISE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3052,21,'DOCUMENTACAO INCOMPLETA, INCORRETA OU AUSENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3053,21,'ELEMENTOS PODEM SER VISUALIZADOS EM UMA MESMA PELICULA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3054,21,'IDENTIFICADO CONDUTO(S) NAO OBTURADO(S)');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3055,21,'IDENTIFICADO TRATAMENTO ENDODÔNTICO E NAO RETRATAMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3056,21,'NA AUDITORIA FOI CONSTATADA DIVERGENCIA NA QUANTIDADE DE FACES RESTAURADAS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3057,21,'NAO APRESENTA A QUANTIDADE MINIMA DE ELEMENTOS DENTARIOS POR SEGMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3058,21,'NECESSARIA AUDITORIA FINAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3059,21,'NECESSARIA AUDITORIA INICIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3060,21,'NECESSARIA AUDITORIA INTERMEDIARIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3061,21,'NECESSARIA AVALIACAO DO ESPECIALISTA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3062,21,'NECESSARIO ENVIAR LAUDO OU RELATORIO TECNICO SOBRE O TRATAMENTO SOLICITADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3063,21,'O PLANO DE TRATAMENTO AUTORIZADO SERA CANCELADO DEVIDO A TROCA DE PROFISSIONAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3064,21,'PROCEDIMENTO AUTORIZADO APENAS PARA DENTES TRATADOS ENDODONTICAMENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3065,21,'PROCEDIMENTO AUTORIZADO SOMENTE PARA DENTES ANTERIORES');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3066,21,'PROCEDIMENTO EM DESACORDO COM O ANEXO GUIA TRATAMENTO ODONTOLOGICO SITUACAO INICIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3067,21,'RADIOGRAFIA FINAL NAO ENVIADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3068,21,'RADIOGRAFIA FINAL SEM DISSOCIACAO DOS CONDUTOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3069,21,'RADIOGRAFIA INDICA A NECESSIDADE DE TRATAMENTO ENDODONTICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3070,21,'RADIOGRAFIA INDICA A PRESENCA DE RAIZ RESIDUAL NO ALVEOLO ');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3071,21,'RADIOGRAFIA INDICA AUSENCIA DE NUCLEO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3072,21,'RADIOGRAFIA INDICA CANAL(AIS) NAO OBTURADO(S)');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3073,21,'RADIOGRAFIA INDICA DESVIO DA TRAJETORIA DO CANAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3074,21,'RADIOGRAFIA INDICA EXCESSO DE MATERIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3075,21,'RADIOGRAFIA INDICA FALHA NA OBTURACAO DO(S) CONDUTO(S)');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3076,21,'RADIOGRAFIA INDICA FALTA DE ADAPTACAO DA COROA/NUCLEO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3077,21,'RADIOGRAFIA INDICA FALTA DE ADAPTACAO DA COROA/PECA PROTETICA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3078,21,'RADIOGRAFIA INDICA NUCLEO INADEQUADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3079,21,'RADIOGRAFIA INDICA TRATAMENTO ENDODÔNTICO E NAO RETRATATAMENTO  ENDODÔNTICO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3080,21,'RADIOGRAFIA INICIAL E FINAL NAO ENVIADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3081,21,'RADIOGRAFIA INICIAL NAO ENVIADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3082,21,'RADIOGRAFIA/IMAGEM INDICA FALHA NA RESTAURACAO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3083,21,'REAVALIAR O PLANO DE TRATAMENTO OBSERVANDO CRITERIOS DE INDICACAO, OPORTUNIDADE E VIABILIDADE.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3084,21,'RELATORIO ANALISE TECNICA SEM CARIMBO/ASSINATURA DO  PRESTADOR');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3085,21,'RADIOGRAFIA NAO CORRESPONDE AO PROCEDIMENTO SOLICITADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3086,21,'TRATAMENTO ODONTOLOGICO NAO CARACTERIZADO COMO URGENCIA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3087,21,'COBRANÇA INDEVIDA DE TAXA ADMINISTRATIVA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3088,21,'VALOR ACATADO, CONFORME REAJUSTE RETROATIVO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3089,21,'QUANTIDADE DE ITENS INCOMPATÍVEL COM O PERÍODO DE INTERNAÇÃO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3090,21,'NECESSÁRIO ENVIAR AS ETIQUETAS E SELOS HEMOTERÁPICOS DO MATERIAL UTILIZADO.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3091,21,'COBRANÇA FORA DO PRAZO ESTIPULADO NO CONTRATO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3092,21,'VALOR ACATADO POR GLOSA REALIZADA INDEVIDAMENTE, APÓS AVALIAÇÃO DO RECURSO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3093,21,'VALOR ACATADO POR AUTORIZAÇÃO ESPECIAL');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3094,21,'VALOR DA TAXA ADMINISTRATIVA ALTERADO EM RAZÃO DE GLOSAS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3095,21,'RECURSO DE GLOSA ACATADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3096,21,'ATENDIMENTO NÃO CONFIRMADO PELO BENEFICIÁRIO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3097,21,'TIPO DE ATENDIMENTO INCOMPATÍVEL COM A SEGMENTAÇÃO ASSISTENCIAL CONTRATADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3098,21,'O PRESTADOR POSSUI PACOTE CONTRATADO PARA ESTE PROCEDIMENTO. VERIFIQUE O CÓDIGO CORRESPONDENTE');
    --
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(3099,21,'Outros');
    -- 22, 'MENSAGENS DE SISTEMA'
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5001,22,'MENSAGEM ELETRÔNICA FORA DO PADRÃO TISS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5002,22,'NÃO FOI POSSÍVEL VALIDAR O ARQUIVO XML ');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5003,22,'ENDEREÇO DO REMETENTE INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5004,22,'ENDEREÇO DO DESTINATÁRIO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5005,22,'REMETENTE NÃO IDENTIFICADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5006,22,'DESTINATÁRIO NÃO IDENTIFICADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5007,22,'MENSAGEM INCONSISTENTE OU INCOMPLETA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5008,22,'ESPAÇO RESERVADO PARA A CAIXA DE SAÍDA INSUFICIENTE  ');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5009,22,'ESPAÇO RESERVADO PARA A CAIXA DE ENTRADA INSUFICIENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5010,22,'ENVIO DE MENSAGEM NÃO FOI TERMINADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5011,22,'ENVIO DE MENSAGEM FINALIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5012,22,'RECEBIMENTO DE MENSAGEM NÃO FINALIZADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5013,22,'RECEBIMENTO DE MENSAGEM FINALIZADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5014,22,'CÓDIGO HASH INVÁLIDO. MENSAGEM PODE ESTAR CORROMPIDA.');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5015,22,'NÚMERO DE GUIAS/DEMONSTRATIVOS DENTRO DA MENSAGEM SUPERIOR AO TAMANHO MÁXIMO PERMITIDO.');
    --Itens existente na base MVDSV e que não constam na planilha
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5016,22,'SEM NENHUMA OCORRENCIA DE MOVIMENTO DE INCLUSAO NA COMPETENCIA PARA ENVIO A ANS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5017,22,'ARQUIVO PROCESSADO PELA ANS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5018,22,'CERTIFICADO DIGITAL INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5019,22,'CERTIFICADO DIGITAL VENCIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5020,22,'CERTIFICADO DIGITAL REVOGADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5021,22,'CADEIA DE CERTIFICAÇÃO INVÁLIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5022,22,'ASSINATURA DIGITAL NÃO CONFERE ');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5023,22,'COMPETÊNCIA NÃO ESTÁ LIBERADA PARA ENVIO DE DADOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5024,22,'OPERADORA INATIVA NA COMPETÊNCIA DOS DADOS');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5025,22,'DATA DE REGISTRO DA TRANSAÇÃO INVÁLIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5026,22,'HORA DE REGISTRO DA TRANSAÇÃO INVÁLIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5027,22,'REGISTRO ANS DA OPERADORA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5028,22,'VERSÃO DO PADRÃO INVÁLIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5029,22,'INDICADOR INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5030,22,'CÓDIGO DO MUNÍCIPIO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5031,22,'CARÁTER DE ATENDIMENTO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5032,22,'INDICADOR DE RECÉM-NATO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5033,22,'MOTIVO DE ENCERRAMENTO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5034,22,'VALOR NÃO INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5035,22,'CÓDIGO DA TABELA DE REFERÊNCIA NÃO INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5036,22,'CÓDIGO DO GRUPO DO PROCEDIMENTO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5037,22,'CÓDIGO DO DENTE INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5038,22,'CÓDIGO DA REGIÃO DA BOCA INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5039,22,'CÓDIGO DA FACE DO DENTE INVÁLIDO ');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5040,22,'VALOR DEVE SER MAIOR QUE ZERO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5041,22,'QUANTIDADE NÃO INFORMADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5042,22,'VALOR INFORMADO DA GUIA DIFERENTE DO SOMATÓRIO DO VALOR INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5043,22,'MOTIVO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5044,22,'JÁ EXISTEM INFORMAÇÕES NA ANS PARA A COMPETÊNCIA INFORMADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5045,22,'COMPETÊNCIA ANTERIOR NÃO ENVIADA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5046,22,'COMPETÊNCIA INVÁLIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5047,22,'NÚMERO DO LOTE NÃO INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5048,22,'DATA DE NASCIMENTO DO BENEFICIÁRIO INVÁLIDA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5049,22,'VALOR TOTAL MENOR QUE ZERO NA GUIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5050,22,'VALOR INFORMADO INVÁLIDO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5051,22,'COMPETENCIA DO ARQUIVO DIFERENTE DA COMPETENCIA DA DATA DE PROCESSA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5052,22,'IDENTIFICADOR INEXISTENTE');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5053,22,'IDENTIFICADOR JÁ INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5054,22,'IDENTIFICADOR NÃO ENCONTRADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5055,22,'IDENTIFICADOR JÁ INFORMADO NA COMPETÊNCIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5056,22,'IDENTIFICADOR NÃO INFORMADO NA COMPETÊNCIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5057,22,'GUIA DE CONSULTA COM MAIS DE UM PROCEDIMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5058,22,'PROCEDIMENTO INCOMPATÍVEL COM O TIPO DE GUIA');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5059,22,'EXCLUSÃO INVÁLIDA - EXISTEM LANÇAMENTOS VINCULADOS A ESTA FORMA DE C');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5060,22,'VALOR TOTAL PAGO DIFERENTE DA SOMA DAS PARCELAS PAGAS NO LANÇAMENTO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5061,22,'TIPO DE ATENDIMENTO OPERADORA INTERMEDIÁRIA NÃO INFORMADO');
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5062,22,'REGISTRO ANS DA OPERADORA INTERMEDIÁRIA NÃO INFORMADO');
    --
    DBAPS.PRC_INSERE_ITGRUPO_GLOSA(5099,22,'Outros');
    --MENSAGENS RESERVADAS

    --Ajstando nome dos grupos
     FOR r IN cGruposGlosa LOOP
         UPDATE dbaps.grupo_motivo_glosa SET  ds_grupo_motivo_glosa = r.ds_grupo
            WHERE  cd_grupo_motivo_glosa = r.cd_grupo_motivo_glosa;
         COMMIT;
    END LOOP;

END;
