--<DS_SCRIPT>
-- DESCRIÇÃO..: Criando a tabela de Cadastro de Usuário
-- RESPONSAVEL: Elias Santana
-- DATA.......: 17/03/2022  22:28
-- APLICAÇÃO..: SYSFATURA - V1.0
--</DS_SCRIPT>

CREATE TABLE CURSOPLSQL.USUARIO (
   CD_USUARIO NUMBER NOT NULL
  ,DT_CADASTRO DATE DEFAULT SYSDATE NOT NULL
  ,LOGIN VARCHAR2(15)
  ,SENHA VARCHAR2(64)
  ,NOME VARCHAR2(60)
  ,SN_ATIVO VARCHAR2(1) DEFAULT 'N' NOT NULL
)
/
COMMENT ON COLUMN CURSOPLSQL.USUARIO.CD_USUARIO IS 'Código do Cliente - PK'
/
COMMENT ON COLUMN CURSOPLSQL.USUARIO.DT_CADASTRO IS 'Data de Cadastro do Usuário'
/
COMMENT ON COLUMN CURSOPLSQL.USUARIO.LOGIN IS 'Login do usuário ex: elias.silva@gmail.com'
/
COMMENT ON COLUMN CURSOPLSQL.USUARIO.senha IS 'Senha do usuário'
/
COMMENT ON COLUMN CURSOPLSQL.USUARIO.nome IS 'Nome do usuário'
/
COMMENT ON COLUMN CURSOPLSQL.USUARIO.sn_ativo IS 'Sinaliza se o usuário está ou não ativo'
/
--CRIANDO A SEQUENCE PARA A TABELA DE USUARIO
CREATE SEQUENCE SEQ_USUARIO
START WITH 1
INCREMENT BY 1
MAXVALUE 999999999999999
NOCYCLE
NOCACHE
/
--CRIANDO CHECK PARA A COLUNA CD_USUARIO
ALTER TABLE cursoplsql.usuario
  ADD CONSTRAINT cnt_usuario_seq CHECK (
  cd_usuario IN ('S','N')
)
/
--CRIANDO CHAVE PRIMÁRIA PARA A TABELA USUÁRIO
ALTER TABLE CURSOPLSQL.USUARIO
    ADD CONSTRAINT cnt_usuario_pk PRIMARY KEY (
    cd_usuario
)

